import { afterEach, describe, expect, it, vi } from "vitest";
import {
  BusinessSemanticsNotFoundError,
  BusinessSemanticsNotReadyError,
  BusinessSemanticsQueryError,
  BusinessSemanticsUnavailableError,
  getActiveModelPassportV2,
  getGeoCatalog,
  getJobResultViewV2,
  getModelOverviewV2,
  getScenarioMediaPlanV2,
  getValidationViewV2,
  getWorkspaceGeoBudget,
  parseGeoCatalog,
  parseJobResultViewV2,
  parseScenarioMediaPlanV2,
  parseValidationViewV2,
  parseWorkspaceGeoBudget,
  UnsupportedBusinessSemanticsContractError,
} from "./business-semantics-client";

const BASE = "http://127.0.0.1:8765";
const JOB_ID = "job_1234567890ab";
const VALIDATION_ID = "validation_1234567890ab";
const GEO = { geo_id: "geo_1234567890abcdef", geo_display_name: "Москва" };
const CHANNEL = { channel_id: "Digital_Performance", channel_display_name: "Цифровая реклама" };
type MutableRecord = Record<string, unknown>;

function response(value: unknown, status = 200): Response { return new Response(JSON.stringify(value), { status, headers: { "Content-Type": "application/json" } }); }
function stub(value: unknown, status = 200) { const fetchMock = vi.fn().mockResolvedValue(response(value, status)); vi.stubGlobal("fetch", fetchMock); return fetchMock; }
function omit(value: MutableRecord, keys: readonly string[]): MutableRecord { const copy = { ...value }; keys.forEach((key) => delete copy[key]); return copy; }
function quantiles(unit: string, available = true, denominator = 1) { return { status: available ? "available" : "unavailable", unit, p10: available ? 8 / denominator : null, p50: available ? 10 / denominator : null, p90: available ? 12 / denominator : null, display_text: available ? "Интервал эффекта." : "Недоступно." }; }
function scenario(id: string, overrides: Record<string, unknown> = {}) {
  const completed = id !== "S06" || overrides.status !== "infeasible";
  const allocated = completed ? 100 : 0;
  return {
    scenario_id: id, name: `Сценарий ${id}`, description: "План распределения бюджета.", scenario_kind: id === "S01" ? "uploaded_plan" : id === "S05" ? "conservative_plan" : id === "S06" ? "optimized_plan" : "benchmark_plan", scenario_variant: id === "S05" ? "full_conservative" : null,
    status: completed ? "completed" : "infeasible", is_recommended: id === "S06", decision_status: id === "S01" ? "keep_uploaded_plan" : id === "S06" ? "recommended_reallocation" : "manual_review_required", review_status: id === "S06" ? "not_required" : "manual_review_required",
    budget: { requested_budget_rub: 100, allocated_budget_rub: allocated, unallocated_budget_rub: 100 - allocated, allocation_share: allocated / 100 },
    incremental_turnover: quantiles("RUB", completed), roas: { allocated_budget: quantiles("ratio", completed, allocated || 1), requested_budget: quantiles("ratio", completed, 100), primary_denominator_kind: "allocated_budget", primary_denominator_budget_rub: allocated },
    risk_budget: { within_support_budget_rub: allocated, within_support_share: allocated ? 1 : null, controlled_extrapolation_budget_rub: 0, controlled_extrapolation_share: allocated ? 0 : null, high_risk_budget_rub: 0, high_risk_share: allocated ? 0 : null, within_support_cells_n: allocated ? 1 : 0, controlled_extrapolation_cells_n: 0, high_risk_cells_n: 0 },
    reliability: { status: "within_support", display_text: "Поддержка достаточна.", evidence_codes: [], safe_rank: id === "S06" ? 1 : null, raw_rank: id === "S06" ? 1 : null }, limiting_constraints: [], ...overrides,
  };
}
function result(overrides: Record<string, unknown> = {}) {
  return { contract_name: "job_result_view_v2", schema_version: "2.0.0", record_origin: "sanitized_fixture", job_id: JOB_ID, result_id: "result_1234567890ab", source_overview_id: "overview_1234567890ab", updated_at_utc: "2026-07-18T10:00:00+00:00",
    campaign: { campaign_id: "campaign_1234567890ab", campaign_name: "Тест", segments: ["Все"], start_date: "2026-08-01", end_date: "2026-08-31", requested_budget_rub: 100, channels: [CHANNEL], geographies_n: 1, geographies: [GEO] },
    recommendation: { decision_status: "recommended_reallocation", review_status: "not_required", scenario_id: "S06", title: "Рекомендация", display_text: "Можно использовать распределение.", decision_scope_text: "Только для allocation." },
    scenarios: ["S01", "S02", "S03", "S04", "S05", "S06"].map((id) => scenario(id)), media_plan: { endpoint: `/api/v1/jobs/${JOB_ID}/media-plan-v2`, selected_scenario_id: "S06" },
    map: { status: "unavailable", display_text: "Координаты не опубликованы.", coordinate_catalog_version: "catalog-v1", geo_points: [{ ...GEO, latitude: null, longitude: null, coordinates_status: "unavailable", region_id: null, region_display_name: null }] }, limitations: [], ...overrides };
}
function plan(overrides: Record<string, unknown> = {}) {
  const row = { scenario_id: "S06", campaign_id: "campaign_1234567890ab", segment: "Все", ...GEO, ...CHANNEL, date: null, source_budget_rub: 100, selected_budget_rub: 100, delta_rub: 0, delta_pct: 0, source_budget_share: 1, selected_budget_share: 1, quality_status: "within_support", quality_display_text: "В поддержке." };
  const channelAggregate = omit(row, ["geo_id", "geo_display_name", "segment", "scenario_id", "campaign_id", "date", "source_budget_share", "selected_budget_share"]);
  const geoAggregate = omit(row, ["channel_id", "channel_display_name", "segment", "scenario_id", "campaign_id", "date", "source_budget_share", "selected_budget_share"]);
  const geoChannelAggregate = omit(row, ["segment", "scenario_id", "campaign_id", "date", "source_budget_share", "selected_budget_share"]);
  return { contract_name: "scenario_media_plan_v2", schema_version: "2.0.0", record_origin: "sanitized_fixture", job_id: JOB_ID, result_id: "result_1234567890ab", campaign_id: "campaign_1234567890ab", scenario: { scenario_id: "S06", title: "Сценарий S06", status: "completed", is_selected: true, safe_rank: 1, raw_rank: 1, quality_status: "within_support", quality_display_text: "В поддержке." }, source_artifact: { artifact_id: "artifact_1234567890ab", kind: "recommended_allocations_csv", sha256: "a".repeat(64) }, grain: "geo_channel_total", filters: { channel_id: null, geo_display_name: null, date: null }, pagination: { page: 1, page_size: 100, total_rows: 1, total_pages: 1 }, totals: { requested_budget_rub: 100, source_budget_rub: 100, selected_budget_rub: 100, unallocated_budget_rub: 0, delta_rub: 0, reconciliation_status: "reconciled" }, filtered_totals: { source_budget_rub: 100, selected_budget_rub: 100, delta_rub: 0 }, rows: [row], aggregates: { by_channel: [channelAggregate], by_geo: [geoAggregate], by_geo_channel: [geoChannelAggregate], by_date: { status: "unavailable", display_text: "Недоступно.", rows: null }, channel_date_matrix: { status: "unavailable", display_text: "Недоступно.", rows: null }, geo_channel_matrix: { status: "ready", display_text: "Готово.", rows: [geoChannelAggregate] } }, map: { status: "unavailable", display_text: "Недоступно.", geo_points: null, coordinate_catalog_version: null }, working_media_plan: { status: "unavailable", display_text: "Недоступно.", artifact: null }, limitations: [], updated_at_utc: "2026-07-18T10:00:00+00:00", ...overrides };
}
function validation(overrides: Record<string, unknown> = {}) { return { contract_name: "validation_result_v2", schema_version: "2.0.0", validation_id: VALIDATION_ID, status: "passed", job_creation_allowed: true, file_validation: { status: "passed", rows_n: 1, campaigns_n: 1, geographies_n: 1, channels_n: 1, requested_budget_rub: 100, blocking_errors_n: 0, warnings_n: 0, checks: [] }, model_limitations: [], geo_points: [{ ...GEO, latitude: null, longitude: null, coordinates_status: "unavailable", budget_rub: 100, budget_share: 1, channels: [CHANNEL], has_model_limitations: false }], ...overrides }; }
function catalog() { return { contract_name: "geo_catalog_v1", schema_version: "1.0.0", catalog_version: "catalog-v1", status: "unavailable", display_text: "Координаты недоступны.", geographies_n: 1, entries: [{ ...GEO, latitude: null, longitude: null, coordinates_status: "unavailable", region_id: null, region_display_name: null }] }; }
function workspace() { return { contract_name: "workspace_geo_budget_v1", schema_version: "1.0.0", catalog_version: "catalog-v1", status: "unavailable", display_text: "Координаты недоступны.", total_budget_rub: 100, campaigns_n: 1, geographies_n: 1, rows: [{ ...GEO, latitude: null, longitude: null, coordinates_status: "unavailable", total_budget_rub: 100, campaigns_n: 1, budget_share: 1 }] }; }
function serving() { return { serving_policy_version: "turnover_serving_v1", target_id: "turnover", core_target: "turnover_per_user", serving_targets_n: 1, active_serving_models_n: 4, research_models_in_package_n: 12, calculation_allowed: true, production_claim_allowed: false }; }
function evidence() { return { status: "passed", generated_at_utc: "2026-07-18T10:00:00+00:00", reason_code: null, display_text: "Проверка пройдена." }; }
function policy() { return { segment: "Все", ...CHANNEL, target: "turnover", allowed_use: "primary", forecast_action: "allowed", optimizer_action: "allowed", display_text: "Доступно." }; }
function passport() { return { contract_name: "model_passport_v2", schema_version: "2.0.0", record_origin: "synthetic_fixture", serving: serving(), package: { registry_channel: "preprod", registry_event_id: "event", package_id: "pkg_1234567890abcdef_1234567890abcdef", package_fingerprint: "b".repeat(64), model_run_id: "run", package_stage: "ready", activation_status: "preprod", package_schema_version: "1", gate_policy_version: "1" }, data: { grain: "daily", training_period: { start_date: "2025-01-01", end_date: "2025-12-31" }, development_shadow_period: { start_date: null, end_date: null, purpose: "development_shadow_not_sealed_oot" } }, coverage: { segments: ["Все"], channels: [CHANNEL], targets: [{ target_id: "turnover", core_target: "turnover_per_user" }], geographies_n: 1, capability_cells_n: 1 }, validation: { historical_replay: evidence(), sealed_oot: { status: "unavailable", generated_at_utc: null, reason_code: "OOT", display_text: "Недоступно." }, production_blockers: [] }, channel_policies: [policy()], caveats: [] }; }
function overview() { return { contract_name: "model_overview_v2", schema_version: "2.0.0", serving: serving(), summary: { training_period: { start_date: "2025-01-01", end_date: "2025-12-31" }, package_status: "ready", activation_status: "preprod", calculation_allowed: true, historical_replay: evidence(), sealed_oot: { status: "unavailable", generated_at_utc: null, reason_code: "OOT", display_text: "Недоступно." } }, channel_policies: [policy()], limitations: [] }; }

afterEach(() => vi.unstubAllGlobals());

describe("business semantics v2 parsers", () => {
  it("accepts the full, turnover-only, six-scenario result projection", () => expect(parseJobResultViewV2(result(), JOB_ID).scenarios).toHaveLength(6));
  it.each([
    ["adds a local path", (value: MutableRecord) => { (value.limitations as MutableRecord[]).push({ code: "X", display_text: "/Users/private" }); }],
    ["reorders S01-S06", (value: MutableRecord) => { const scenarios = value.scenarios as unknown[]; [scenarios[0], scenarios[1]] = [scenarios[1], scenarios[0]]; }],
    ["recommends partial S5", (value: MutableRecord) => { (value.scenarios as unknown[])[4] = scenario("S05", { scenario_variant: "safe_partial", is_recommended: true, decision_status: "no_safe_recommendation", budget: { requested_budget_rub: 100, allocated_budget_rub: 80, unallocated_budget_rub: 20, allocation_share: .8 } }); }],
    ["makes S6 partial", (value: MutableRecord) => { const budget = ((value.scenarios as MutableRecord[])[5].budget as MutableRecord); budget.allocated_budget_rub = 90; budget.unallocated_budget_rub = 10; }],
    ["uses a fake S6 KPI", (value: MutableRecord) => { (value.scenarios as unknown[])[5] = scenario("S06", { status: "infeasible", is_recommended: false, decision_status: "no_safe_recommendation", incremental_turnover: quantiles("RUB", true) }); value.recommendation = { ...(value.recommendation as MutableRecord), decision_status: "no_safe_recommendation", scenario_id: null }; (value.media_plan as MutableRecord).selected_scenario_id = null; }],
    ["leaks orders into presentation", (value: MutableRecord) => { (value.recommendation as MutableRecord).display_text = "orders are shown"; }],
    ["leaks a raw channel id into constraints", (value: MutableRecord) => { ((value.scenarios as MutableRecord[])[4].limiting_constraints as string[]).push("Ограничение Digital_Performance"); }],
    ["uses an internal S5.1 label", (value: MutableRecord) => { (value.scenarios as MutableRecord[])[4].description = "Внутренний вариант S5.1"; }],
    ["uses a truncated presentation list", (value: MutableRecord) => { (value.recommendation as MutableRecord).display_text = "Москва ... ещё 14"; }],
  ])("rejects result that %s", (_name, mutate) => { const value = result(); mutate(value); expect(() => parseJobResultViewV2(value, JOB_ID)).toThrow(UnsupportedBusinessSemanticsContractError); });
  it("requires exact quantiles and explicit ROAS denominator", () => { const value = result(); value.scenarios[5].incremental_turnover.p10 = 11; expect(() => parseJobResultViewV2(value, JOB_ID)).toThrow(UnsupportedBusinessSemanticsContractError); });
  it("rejects ROAS quantiles that do not equal turnover divided by the stated budgets", () => { const value = result(); value.scenarios[5].roas.requested_budget.p50 = .11; expect(() => parseJobResultViewV2(value, JOB_ID)).toThrow(UnsupportedBusinessSemanticsContractError); });
  it("accepts an explicit S6 infeasibility without a fake KPI", () => { const value = result() as unknown as MutableRecord; (value.scenarios as unknown[])[5] = scenario("S06", { scenario_variant: "infeasible", status: "infeasible", is_recommended: false, decision_status: "unavailable", review_status: "manual_review_required", budget: { requested_budget_rub: 100, allocated_budget_rub: 0, unallocated_budget_rub: 100, allocation_share: 0 }, incremental_turnover: quantiles("RUB", false), roas: { allocated_budget: quantiles("ratio", false), requested_budget: quantiles("ratio", false), primary_denominator_kind: "allocated_budget", primary_denominator_budget_rub: 0 }, risk_budget: { within_support_budget_rub: 0, within_support_share: null, controlled_extrapolation_budget_rub: 0, controlled_extrapolation_share: null, high_risk_budget_rub: 0, high_risk_share: null, within_support_cells_n: 0, controlled_extrapolation_cells_n: 0, high_risk_cells_n: 0 }, limiting_constraints: ["Ограничение поддержки."] }); value.recommendation = { ...(value.recommendation as MutableRecord), decision_status: "keep_uploaded_plan", review_status: "manual_review_required", scenario_id: "S01" }; (value.media_plan as MutableRecord).selected_scenario_id = "S01"; expect(parseJobResultViewV2(value, JOB_ID).scenarios[5].status).toBe("infeasible"); });
  it("cross-checks media-plan rows, totals and aggregates", () => expect(parseScenarioMediaPlanV2(plan(), JOB_ID, { scenarioId: "S06" }, parseJobResultViewV2(result(), JOB_ID)).rows).toHaveLength(1));
  it("accepts a viewed media plan that is not the recommended scenario", () => { const resultValue = result(); resultValue.scenarios[5].is_recommended = false; resultValue.scenarios[5].decision_status = "manual_review_required"; resultValue.scenarios[5].review_status = "manual_review_required"; resultValue.recommendation = { ...resultValue.recommendation, decision_status: "keep_uploaded_plan", review_status: "manual_review_required", scenario_id: "S01" }; resultValue.media_plan.selected_scenario_id = "S01"; const expected = parseJobResultViewV2(resultValue, JOB_ID); const value = plan(); value.scenario.is_selected = false; expect(parseScenarioMediaPlanV2(value, JOB_ID, { scenarioId: "S06" }, expected).scenario.is_selected).toBe(false); });
  it("uses segment, geo and channel as the media row identity", () => { const value = plan(); const first = value.rows[0]; value.rows = [{ ...first, segment: "A", source_budget_rub: 50, selected_budget_rub: 50, source_budget_share: .5, selected_budget_share: .5 }, { ...first, segment: "B", source_budget_rub: 50, selected_budget_rub: 50, source_budget_share: .5, selected_budget_share: .5 }]; value.pagination.total_rows = 2; value.pagination.total_pages = 1; expect(parseScenarioMediaPlanV2(value, JOB_ID, { scenarioId: "S06" }, parseJobResultViewV2(result(), JOB_ID)).rows).toHaveLength(2); });
  it("accepts the authoritative one-ruble money tolerance", () => { const value = plan(); value.totals.requested_budget_rub = 100.5; expect(parseScenarioMediaPlanV2(value, JOB_ID, { scenarioId: "S06" }, parseJobResultViewV2(result(), JOB_ID)).totals.requested_budget_rub).toBe(100.5); });
  it("rejects unreconciled media-plan aggregate", () => { const value = plan(); value.aggregates.by_geo[0].selected_budget_rub = 98.9; expect(() => parseScenarioMediaPlanV2(value, JOB_ID, { scenarioId: "S06" }, parseJobResultViewV2(result(), JOB_ID))).toThrow(UnsupportedBusinessSemanticsContractError); });
  it.each(["result_id", "campaign_id"] as const)("rejects media-plan with a mismatched %s", (field) => { const value = plan(); value[field] = `${field}_different`; expect(() => parseScenarioMediaPlanV2(value, JOB_ID, { scenarioId: "S06" }, parseJobResultViewV2(result(), JOB_ID))).toThrow(UnsupportedBusinessSemanticsContractError); });
  it("rejects media-plan totals that disagree with the selected result scenario", () => { const value = plan(); value.totals.selected_budget_rub = 98.9; value.totals.unallocated_budget_rub = 1.1; value.totals.delta_rub = -1.1; expect(() => parseScenarioMediaPlanV2(value, JOB_ID, { scenarioId: "S06" }, parseJobResultViewV2(result(), JOB_ID))).toThrow(UnsupportedBusinessSemanticsContractError); });
  it("accepts a passed file that model limitations block", () => { const value = validation({ status: "warning", job_creation_allowed: false }); expect(parseValidationViewV2(value, VALIDATION_ID).job_creation_allowed).toBe(false); });
  it("rejects a channel display name outside the authoritative catalog", () => { const value = validation(); value.geo_points[0].channels[0] = { channel_id: "Digital_Performance", channel_display_name: "Digital_Performance" }; expect(() => parseValidationViewV2(value, VALIDATION_ID)).toThrow(UnsupportedBusinessSemanticsContractError); });
  it("rejects truncated geo strings in validation/catalog/workspace", () => { const validationValue = validation(); validationValue.geo_points[0].geo_display_name = "Москва ... еще 2"; expect(() => parseValidationViewV2(validationValue, VALIDATION_ID)).toThrow(UnsupportedBusinessSemanticsContractError); const catalogValue = catalog(); catalogValue.entries[0].geo_display_name = "Москва ... еще 2"; expect(() => parseGeoCatalog(catalogValue)).toThrow(UnsupportedBusinessSemanticsContractError); const workspaceValue = workspace(); workspaceValue.rows[0].budget_share = .5; expect(() => parseWorkspaceGeoBudget(workspaceValue)).toThrow(UnsupportedBusinessSemanticsContractError); });
});

describe("business semantics v2 getters", () => {
  it("uses credentialed fetch and the seven canonical paths", async () => {
    const values = [result(), plan(), validation(), passport(), overview(), catalog(), workspace()]; const fetchMock = vi.fn().mockImplementation(() => Promise.resolve(response(values.shift()))); vi.stubGlobal("fetch", fetchMock);
    const expectedResult = parseJobResultViewV2(result(), JOB_ID); await getJobResultViewV2(JOB_ID, undefined, BASE); await getScenarioMediaPlanV2(JOB_ID, { scenarioId: "S06", page: 1, pageSize: 100 }, expectedResult, undefined, BASE); await getValidationViewV2(VALIDATION_ID, undefined, BASE); await getActiveModelPassportV2(undefined, BASE); await getModelOverviewV2(undefined, BASE); await getGeoCatalog(undefined, BASE); await getWorkspaceGeoBudget(undefined, BASE);
    expect(fetchMock.mock.calls.map(([path]) => path)).toEqual([`${BASE}/api/v1/jobs/${JOB_ID}/result-view-v2`, `${BASE}/api/v1/jobs/${JOB_ID}/media-plan-v2?scenario_id=S06&page=1&page_size=100`, `${BASE}/api/v1/validations/${VALIDATION_ID}/view-v2`, `${BASE}/api/v1/models/active-v2`, `${BASE}/api/v1/model/overview-v2`, `${BASE}/api/v1/meta/geo-catalog`, `${BASE}/api/v1/workspace/geo-budget`]);
    expect(fetchMock.mock.calls.every(([, init]) => init.credentials === "include")).toBe(true);
  });
  it("maps stable server coordinates and does not expose the raw payload", async () => { stub({ error: { code: "RESOURCE_NOT_READY", display_text: "private", retryable: true, user_action: "private" } }, 404); await expect(getJobResultViewV2(JOB_ID, undefined, BASE)).rejects.toBeInstanceOf(BusinessSemanticsNotReadyError); stub({ error: { code: "NOT_FOUND", display_text: "private", retryable: false, user_action: "private" } }, 404); await expect(getGeoCatalog(undefined, BASE)).rejects.toBeInstanceOf(BusinessSemanticsNotFoundError); stub({ error: { code: "X", display_text: "private", retryable: true, user_action: "private" } }, 503); await expect(getGeoCatalog(undefined, BASE)).rejects.toBeInstanceOf(BusinessSemanticsUnavailableError); });
  it("validates query before issuing a request", async () => { await expect(getScenarioMediaPlanV2(JOB_ID, { scenarioId: "S06", page: 0 }, parseJobResultViewV2(result(), JOB_ID), undefined, BASE)).rejects.toBeInstanceOf(BusinessSemanticsQueryError); });
  it("uses the specified malformed-result message", async () => { stub({ contract_name: "job_result_view_v2" }); const error = await getJobResultViewV2(JOB_ID, undefined, BASE).catch((item) => item); expect(error).toBeInstanceOf(UnsupportedBusinessSemanticsContractError); expect((error as Error).message).toBe("Данные результата имеют неподдерживаемый формат."); });
});
